FROM node:25-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json tsconfig.json
COPY vite.config.ts vite.config.ts

RUN npm i
COPY src src
COPY public public

ENTRYPOINT [ "npm", "run", "dev" ]