FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]







#//TODO: Fix the CI - Docker builder
# ------------------------------
# STAGE 1 — Development
# ------------------------------
# FROM node:20-alpine AS dev

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 5173

# CMD ["npm", "run", "dev"]


# # ------------------------------
# # STAGE 2 — Build
# # ------------------------------
# FROM node:20-alpine AS build

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .
# RUN npm run build


# # ------------------------------
# # STAGE 3 — Production (Nginx)
# # ------------------------------
# FROM nginx:1.27-alpine AS prod

# COPY nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /app/dist /usr/share/nginx/html

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]
