FROM node:lts

# RUN apk --no-cache add curl

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json tsconfig.json
COPY jest.config.js jest.config.js

RUN npm i
COPY src src

ENTRYPOINT ["npm","run","dev"]