FROM node:25-alpine

RUN apk --no-cache add curl

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json tsconfig.json
COPY jest.config.ts jest.config.ts

RUN npm i
COPY src src

ENTRYPOINT ["npm","run","dev"]